import Navbar from "@components/Navbar";
import "../globals.css";
import Layout from "@components/admin/Layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Adminayout({ children }) {
  return (
    <Layout>
      <div className=" ">{children}</div>
    </Layout>
  );
}
